FROM golang:1.17.8-alpine AS builder

ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64

WORKDIR /usr/local

COPY . /usr/local/

RUN go mod download

RUN go build -o /bin/script

FROM scratch

COPY --from=builder /bin/script /sbin/script

CMD ["/sbin/script"]